from __future__ import division, print_function
from pytelemetry import Pytelemetry
try:
    from queue import Queue  # Python 3
except ImportError:
    from Queue import Queue  # Python 2
import pytest
import six

# For Python 2 compatibility, if unittest.mock is not available
try:
    import unittest.mock as mock
except ImportError:
    try:
        import mock
    except ImportError:
        print("WARNING: mock module not available, some tests may fail")
        mock = None

class transportMock:
    def __init__(self):
        self.queue = Queue()
        
    def read(self, maxbytes=1):
        data = []
        amount = 0
        while amount < maxbytes and not self.queue.empty():
            c = self.queue.get()
            data.append(c)
            amount += 1
        return data

    def readable(self):
        return self.queue.qsize()

    def write(self, data):
        for i in range(len(data)):
            self.queue.put(data[i])
        return 0

    def writeable(self):
        return not self.queue.full()

def test_wrong_type():
    # Setup
    t = transportMock()
    c = Pytelemetry(t)

    with pytest.raises(Exception) as excinfo:
        c.publish('sometopic',12,'string')
    # TODO : Assert exception
    assert t.queue.qsize() == 0

def test_unexisting_type():
    # Setup
    t = transportMock()
    c = Pytelemetry(t)

    with pytest.raises(IndexError):
        c.publish('sometopic',12,'int323')
    assert t.queue.qsize() == 0

def test_hardcoded():
    t = transportMock()
    c = Pytelemetry(t)
    cb = mock.Mock(spec=["topic","data"])
    c.subscribe('sometopic ',cb)

    # Apply hardcoded frame directly generated by the c library
    # Use bytearray to ensure compatibility with both Python 2 and 3
    t.write(bytearray([247, 6, 0, 115, 111, 109, 101, 116, 111, 112, 105, 99, 32, 0, 169, 48, 0, 0, 111, 249, 127]))
    c.update()
    assert t.queue.qsize() == 0
    cb.assert_called_once_with('sometopic ',12457, None)

# TODO : Check what happens is string is non null terminated

# TODO : Check what happens if there are spaces in name

# TODO Check wrong crc
